import { authorize,requireRole,db,body,json,failure,audit,ApiError,beginIdempotency,completeIdempotency,releaseIdempotency } from "@/lib/server";
import { projectInput,projectActionInput } from "@/lib/domain";
import { decodeCursor,optionalSearch,pageLimit,pageResult } from "@/lib/pagination";
export async function GET(request:Request){try{
 const url=new URL(request.url),wid=url.searchParams.get("workspace")||"";
 await authorize(wid);
 const projectId=url.searchParams.get("id")||"";
 if(projectId){if(projectId.length>200)throw new ApiError(400,"project id is too long.");const item=await db().prepare("SELECT p.id,p.name,p.client,p.client_email,p.scope,p.budget,p.rate,p.due_date,p.created_at,p.archived_at,COALESCE((SELECT pa.scope FROM project_amendments pa WHERE pa.project_id=p.id ORDER BY pa.version DESC LIMIT 1),p.scope) AS effective_scope,COALESCE((SELECT pa.budget FROM project_amendments pa WHERE pa.project_id=p.id ORDER BY pa.version DESC LIMIT 1),p.budget) AS effective_budget,COALESCE((SELECT pa.rate FROM project_amendments pa WHERE pa.project_id=p.id ORDER BY pa.version DESC LIMIT 1),p.rate) AS effective_rate,COALESCE((SELECT pa.due_date FROM project_amendments pa WHERE pa.project_id=p.id ORDER BY pa.version DESC LIMIT 1),p.due_date) AS effective_due_date,COALESCE((SELECT pa.version FROM project_amendments pa WHERE pa.project_id=p.id ORDER BY pa.version DESC LIMIT 1),0) AS amendment_version,(SELECT COUNT(*) FROM changes c WHERE c.project_id=p.id AND c.workspace_id=p.workspace_id) AS change_count,(SELECT COALESCE(SUM(c.approved_amount),0) FROM changes c WHERE c.project_id=p.id AND c.workspace_id=p.workspace_id AND c.status IN ('approved','delivered')) AS approved_additions FROM projects p WHERE p.workspace_id=? AND p.id=?").bind(wid,projectId).first();if(!item)throw new ApiError(404,"Project not found.");return json({item});}
 const limit=pageLimit(url),cursor=decodeCursor(url.searchParams.get("cursor")),search=optionalSearch(url.searchParams.get("search")),status=url.searchParams.get("status")||"all";
 if(!["all","active","archived"].includes(status))throw new ApiError(400,"status must be all, active, or archived.");
 const prefix=search.replace(/[\\%_]/g,"\\$&")+"%",cursorAt=cursor?.createdAt||"",cursorId=cursor?.id||"";
 const rows=await db().prepare("SELECT p.id,p.name,p.client,p.client_email,p.scope,p.budget,p.rate,p.due_date,p.created_at,p.archived_at,COALESCE((SELECT pa.scope FROM project_amendments pa WHERE pa.project_id=p.id ORDER BY pa.version DESC LIMIT 1),p.scope) AS effective_scope,COALESCE((SELECT pa.budget FROM project_amendments pa WHERE pa.project_id=p.id ORDER BY pa.version DESC LIMIT 1),p.budget) AS effective_budget,COALESCE((SELECT pa.rate FROM project_amendments pa WHERE pa.project_id=p.id ORDER BY pa.version DESC LIMIT 1),p.rate) AS effective_rate,COALESCE((SELECT pa.due_date FROM project_amendments pa WHERE pa.project_id=p.id ORDER BY pa.version DESC LIMIT 1),p.due_date) AS effective_due_date,COALESCE((SELECT pa.version FROM project_amendments pa WHERE pa.project_id=p.id ORDER BY pa.version DESC LIMIT 1),0) AS amendment_version,(SELECT COUNT(*) FROM changes c WHERE c.project_id=p.id AND c.workspace_id=p.workspace_id) AS change_count,(SELECT COALESCE(SUM(c.approved_amount),0) FROM changes c WHERE c.project_id=p.id AND c.workspace_id=p.workspace_id AND c.status IN ('approved','delivered')) AS approved_additions FROM projects p WHERE p.workspace_id=? AND (?='all' OR (?='active' AND p.archived_at='') OR (?='archived' AND p.archived_at<>'')) AND (?='' OR p.name LIKE ? ESCAPE '\\' OR p.client LIKE ? ESCAPE '\\') AND (?='' OR p.created_at<? OR (p.created_at=? AND p.id<?)) ORDER BY p.created_at DESC,p.id DESC LIMIT ?").bind(wid,status,status,status,search,prefix,prefix,cursorAt,cursorAt,cursorAt,cursorId,limit+1).all<{id:string;created_at:string}>();
 return json(pageResult(rows.results as ({id:string;created_at:string}&Record<string,unknown>)[],limit));
}catch(e){return failure(e);}}
export async function POST(request:Request){try{const wid=new URL(request.url).searchParams.get("workspace")||"";const {w,u}=await authorize(wid);requireRole(w.role,["owner","editor"]);const v=projectInput.parse(await body(request));const idem=await beginIdempotency(request,wid,u.userId,"project.create",v);if(idem.kind==="replay")return idem.response;try{const count=await db().prepare("SELECT COUNT(*) AS n FROM projects WHERE workspace_id=?").bind(wid).first<{n:number}>();if((count?.n||0)>=200)throw new ApiError(409,"This workspace has reached the 200-project pilot limit.");const id=crypto.randomUUID(),data={id},operations=[db().prepare("INSERT INTO projects(id,workspace_id,name,client,client_email,scope,budget,rate,due_date,created_at,archived_at) VALUES(?,?,?,?,?,?,?,?,?,?,'')").bind(id,wid,v.name,v.client,v.client_email,v.scope,v.budget,v.rate,v.due_date,new Date().toISOString()),audit(wid,id,"Project created",u.email,v.name+" — original baseline recorded")],completion=completeIdempotency(idem,data,201);if(completion)operations.push(completion);await db().batch(operations);return json(data,201);}catch(e){await releaseIdempotency(idem);throw e;}}catch(e){return failure(e);}}
export async function PATCH(request:Request){try{const wid=new URL(request.url).searchParams.get("workspace")||"";const {w,u}=await authorize(wid);requireRole(w.role,["owner","editor"]);const v=projectActionInput.parse(await body(request));const p=await db().prepare("SELECT id,name,archived_at FROM projects WHERE id=? AND workspace_id=?").bind(v.id,wid).first<{id:string;name:string;archived_at:string}>();if(!p)throw new ApiError(404,"Project not found.");const now=new Date().toISOString();if(v.action==="archive"){if(p.archived_at)throw new ApiError(409,"Project is already archived.");const active=await db().prepare("SELECT COUNT(*) AS n FROM changes WHERE project_id=? AND workspace_id=? AND status IN ('draft','pending','approved')").bind(v.id,wid).first<{n:number}>();if((active?.n||0)>0)throw new ApiError(409,"Resolve or withdraw active change requests before archiving this project.");await db().batch([db().prepare("UPDATE projects SET archived_at=? WHERE id=? AND workspace_id=? AND archived_at='' ").bind(now,v.id,wid),audit(wid,v.id,"Project archived",u.email,p.name)]);return json({id:v.id,archived:true});}if(v.action==="restore"){if(!p.archived_at)throw new ApiError(409,"Project is already active.");await db().batch([db().prepare("UPDATE projects SET archived_at='' WHERE id=? AND workspace_id=?").bind(v.id,wid),audit(wid,v.id,"Project restored",u.email,p.name)]);return json({id:v.id,archived:false});}if(p.archived_at)throw new ApiError(409,"Restore this project before adding an amendment.");const amendmentId=crypto.randomUUID();await db().batch([db().prepare("INSERT INTO project_amendments(id,workspace_id,project_id,version,scope,budget,rate,due_date,reason,created_by,created_at) SELECT ?,?,?,COALESCE(MAX(version),0)+1,?,?,?,?,?,?,? FROM project_amendments WHERE project_id=?").bind(amendmentId,wid,v.id,v.scope,v.budget,v.rate,v.due_date,v.reason,u.email,now,v.id),audit(wid,v.id,"Project baseline amended",u.email,p.name+" — "+v.reason)]);return json({id:v.id,amendment_id:amendmentId});}catch(e){return failure(e);}}
