// Execute the actual TypeScript API routes against SQLite, with only the hosting
// identity transport and D1 adapter substituted. No production authentication bypass.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const fs=require('node:fs');
const path=require('node:path');
const ts=require('typescript');
const database=new DatabaseSync(':memory:');
database.exec('PRAGMA foreign_keys=ON');
for(const name of fs.readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())database.exec(fs.readFileSync('drizzle/'+name,'utf8'));
let user={id:'alice',email:'alice@example.com'};
const env={DB:{prepare(sql){return {args:[],bind(...args){this.args=args;return this},async first(){return database.prepare(sql).get(...this.args)||null},async all(){return {results:database.prepare(sql).all(...this.args)}},_run(){const stmt=database.prepare(sql);if(/^SELECT/i.test(sql.trim()))return {results:stmt.all(...this.args),meta:{changes:0}};const r=stmt.run(...this.args);return {results:[],meta:{changes:Number(r.changes)}}}}},async batch(statements){database.exec('BEGIN');try{const result=statements.map(s=>s._run());database.exec('COMMIT');return result}catch(e){database.exec('ROLLBACK');throw e}}}};
const cache=new Map();
function load(file){const abs=path.resolve(file);if(cache.has(abs))return cache.get(abs).exports;const mod={exports:{}};cache.set(abs,mod);const code=ts.transpileModule(fs.readFileSync(abs,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const req=(name)=>{if(name==='cloudflare:workers')return {env};if(name==='next/headers')return {headers:async()=>new Headers(user?{'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email}:{})};if(name==='next/navigation')return {redirect:()=>{throw Error('Unexpected redirect')}};if(name.startsWith('@/'))return load(name.slice(2)+'.ts');if(name.startsWith('.'))return load(path.join(path.dirname(abs),name)+'.ts');return require(name)};new Function('require','module','exports',code)(req,mod,mod.exports);return mod.exports;}
const workspace=load('app/api/workspace/route.ts'),projects=load('app/api/projects/route.ts'),changes=load('app/api/changes/route.ts'),members=load('app/api/members/route.ts'),exporter=load('app/api/export/route.ts'),domain=load('lib/domain.ts');
function req(route,method='GET',payload,extra={}){return new Request('https://scopeledger.test/api/'+route,{method,headers:{'Content-Type':'application/json',Origin:'https://scopeledger.test',...extra},body:payload===undefined?undefined:JSON.stringify(payload)})}
let wid,pid,cid;
const project={name:'Delivery portal',client:'Client A',client_email:'client@example.com',scope:'Shipment listing and invoice download. No SMS.',budget:10000000,rate:250000,due_date:'2026-12-01'};
const change={title:'Add SMS tracking',description:'Add SMS notifications excluded from original scope.',source:'Client email dated 14 September 2026',minutes:95,delay_days:2,due_date:'2026-10-01'};
test('API lifecycle, access control, export, and transactional history',async t=>{
 await t.test('anonymous requests are rejected without disclosing records',async()=>{user=null;const r=await workspace.GET(req('workspace'));assert.equal(r.status,401);user={id:'alice',email:'alice@example.com'}});
 await t.test('read does not create a workspace',async()=>{const r=await workspace.GET(req('workspace'));assert.equal(r.status,200);assert.equal((await r.json()).workspaces.length,0)});
 await t.test('create workspace and read persisted empty records',async()=>{const r=await workspace.POST(req('workspace','POST',{name:'Alice Studio',currency:'INR',demo:false}));assert.equal(r.status,201);wid=(await r.json()).id;const data=await (await workspace.GET(req('workspace?id='+wid))).json();assert.equal(data.workspace.role,'owner');assert.equal(data.events.length,1)});
 await t.test('cross-origin writes are rejected',async()=>{const r=await projects.POST(req('projects?workspace='+wid,'POST',project,{Origin:'https://evil.test'}));assert.equal(r.status,403)});
 await t.test('invalid dates and negative prices are rejected',async()=>{for(const v of [{...project,due_date:'2026-02-31'},{...project,budget:-100}])assert.equal((await projects.POST(req('projects?workspace='+wid,'POST',v))).status,400)});
 await t.test('project stores the immutable baseline',async()=>{const r=await projects.POST(req('projects?workspace='+wid,'POST',project));assert.equal(r.status,201);pid=(await r.json()).id;assert.equal(database.prepare('SELECT scope FROM projects WHERE id=?').get(pid).scope,project.scope)});
 await t.test('tenant isolation hides another company from signed-in outsiders',async()=>{user={id:'bob',email:'bob@example.com'};assert.equal((await workspace.GET(req('workspace?id='+wid))).status,404);assert.equal((await exporter.GET(req('export?workspace='+wid))).status,404);assert.equal((await changes.POST(req('changes?workspace='+wid,'POST',{...change,project_id:pid}))).status,404);user={id:'alice',email:'alice@example.com'}});
 await t.test('foreign project IDs are rejected even for an owner',async()=>{assert.equal((await changes.POST(req('changes?workspace='+wid,'POST',{...change,project_id:'another-tenant'}))).status,404)});
 await t.test('estimate is calculated server-side in integer minor units',async()=>{const r=await changes.POST(req('changes?workspace='+wid,'POST',{...change,project_id:pid}));assert.equal(r.status,201);cid=(await r.json()).id;const row=database.prepare('SELECT * FROM changes WHERE id=?').get(cid);assert.equal(row.amount,395833);assert.equal(row.rate,250000);assert.equal(row.status,'pending');assert.equal((await changes.POST(req('changes?workspace='+wid,'POST',{...change,project_id:pid,amount:1}))).status,400)});
 await t.test('approval requires evidence and an approver email',async()=>{assert.equal((await changes.PATCH(req('changes?workspace='+wid,'PATCH',{id:cid,version:1,status:'approved',evidence:'',approver:''}))).status,400)});
 await t.test('viewer can read but cannot change or grant access',async()=>{assert.equal((await members.POST(req('members?workspace='+wid,'POST',{email:'viewer@example.com',role:'viewer'}))).status,200);user={id:'viewer',email:'viewer@example.com'};assert.equal((await workspace.GET(req('workspace?id='+wid))).status,200);assert.equal((await projects.POST(req('projects?workspace='+wid,'POST',project))).status,403);assert.equal((await members.POST(req('members?workspace='+wid,'POST',{email:'intruder@example.com',role:'reviewer'}))).status,403);user={id:'alice',email:'alice@example.com'}});
 await t.test('editor cannot approve, reviewer can',async()=>{await members.POST(req('members?workspace='+wid,'POST',{email:'editor@example.com',role:'editor'}));user={id:'editor',email:'editor@example.com'};const payload={id:cid,version:1,status:'approved',evidence:'Client approved the quoted fee and scope by email on 14 September.',approver:'client@example.com'};assert.equal((await changes.PATCH(req('changes?workspace='+wid,'PATCH',payload))).status,403);user={id:'alice',email:'alice@example.com'};await members.POST(req('members?workspace='+wid,'POST',{email:'reviewer@example.com',role:'reviewer'}));user={id:'reviewer',email:'reviewer@example.com'};assert.equal((await changes.PATCH(req('changes?workspace='+wid,'PATCH',payload))).status,200);user={id:'alice',email:'alice@example.com'}});
 await t.test('stale approvals do not mutate history',async()=>{const before=database.prepare('SELECT COUNT(*) AS n FROM events').get().n;assert.equal((await changes.PATCH(req('changes?workspace='+wid,'PATCH',{id:cid,version:1,status:'approved',evidence:'Duplicate stale approval evidence.',approver:'client@example.com'}))).status,409);assert.equal(database.prepare('SELECT COUNT(*) AS n FROM events').get().n,before)});
 await t.test('delivery preserves approval evidence and adds separate delivery history',async()=>{const before=database.prepare('SELECT evidence FROM changes WHERE id=?').get(cid).evidence;const r=await changes.PATCH(req('changes?workspace='+wid,'PATCH',{id:cid,version:2,status:'delivered',evidence:'Delivered to client staging environment on 15 September.'}));assert.equal(r.status,200);const row=database.prepare('SELECT * FROM changes WHERE id=?').get(cid);assert.equal(row.status,'delivered');assert.equal(row.version,3);assert.equal(row.evidence,before);assert.match(database.prepare("SELECT detail FROM events WHERE entity_id=? AND action='Status: delivered'").get(cid).detail,/staging environment/)});
 await t.test('terminal requests cannot be approved again',async()=>{assert.equal((await changes.PATCH(req('changes?workspace='+wid,'PATCH',{id:cid,version:3,status:'approved',evidence:'Cannot approve terminal delivery again.',approver:'client@example.com'}))).status,403)});
 await t.test('CSV exports contain real records and neutralize formula injection',async()=>{const r=await exporter.GET(req('export?workspace='+wid));assert.equal(r.status,200);assert.match(await r.text(),/395833/);assert.equal(domain.csvCell('=HYPERLINK("evil")'),'"\'=HYPERLINK(""evil"")"');assert.equal(domain.csvCell('\t+cmd'),'"\'\t+cmd"');const audit=await (await exporter.GET(req('export?workspace='+wid+'&type=audit'))).text();assert.match(audit,/Status: delivered/)});
 await t.test('revoking access removes it immediately',async()=>{assert.equal((await members.DELETE(req('members?workspace='+wid,'DELETE',{email:'viewer@example.com'}))).status,200);user={id:'viewer',email:'viewer@example.com'};assert.equal((await workspace.GET(req('workspace?id='+wid))).status,404);user={id:'alice',email:'alice@example.com'}});
 await t.test('sample data is explicitly flagged and separated',async()=>{const r=await workspace.POST(req('workspace','POST',{name:'Demo',currency:'INR',demo:true}));assert.equal(r.status,201);const id=(await r.json()).id;const d=await (await workspace.GET(req('workspace?id='+id))).json();assert.equal(d.workspace.demo,1);assert.equal(d.projects.length,3);assert.equal(d.changes.length,5);assert.match(d.changes.find(c=>c.status==='approved').evidence,/Fictional/);const original=await (await workspace.GET(req('workspace?id='+wid))).json();assert.equal(original.projects.length,1);assert.equal(original.changes.length,1)});
 await t.test('SQLite foreign keys and indexed isolation queries are enabled',()=>{assert.equal(database.prepare('PRAGMA foreign_keys').get().foreign_keys,1);const plan=database.prepare('EXPLAIN QUERY PLAN SELECT * FROM changes WHERE workspace_id=?').all(wid);assert.ok(plan.some(x=>x.detail.includes('idx_changes_workspace')))});
});
