import { env } from "cloudflare:workers";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { ZodError } from "zod";
import type { Role } from "./domain";
export class ApiError extends Error {constructor(public status:number,message:string){super(message);}}
export function db(){if(!env.DB)throw new ApiError(503,"Records are temporarily unavailable. Please try again.");return env.DB;}
export async function identity(){const u=await getChatGPTUser();if(!u)throw new ApiError(401,"Sign in with ChatGPT to open your workspace.");return {...u,email:u.email.toLowerCase()};}
export async function authorize(id:string){const u=await identity();const w=await db().prepare("SELECT w.*, CASE WHEN w.owner_id=? THEN 'owner' ELSE m.role END AS role FROM workspaces w LEFT JOIN members m ON m.workspace_id=w.id AND m.email=? WHERE w.id=? AND (w.owner_id=? OR m.id IS NOT NULL)").bind(u.userId,u.email,id,u.userId).first<{id:string;owner_id:string;name:string;currency:string;demo:number;role:Role}>();if(!w)throw new ApiError(404,"Workspace not found or access was removed.");return {u,w};}
export function requireRole(role:Role,roles:Role[]){if(!roles.includes(role))throw new ApiError(403,"Your workspace role does not allow this action.");}
export async function body(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new ApiError(403,"Cross-origin changes are not allowed.");if(request.headers.get("sec-fetch-site")==="cross-site")throw new ApiError(403,"Cross-site changes are not allowed.");if(!request.headers.get("content-type")?.includes("application/json"))throw new ApiError(415,"Use JSON for this request.");const raw=await request.text();if(raw.length>30000)throw new ApiError(413,"This request is too large.");try{return JSON.parse(raw);}catch{throw new ApiError(400,"Invalid JSON.");}}
export function audit(workspace:string,entity:string,action:string,actor:string,detail:string){return db().prepare("INSERT INTO events(id,workspace_id,entity_id,action,actor,detail,created_at) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),workspace,entity,action,actor,detail,new Date().toISOString());}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer","X-Frame-Options":"DENY","Permissions-Policy":"camera=(), microphone=(), geolocation=()"}});}
export function randomToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));return Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");}
export async function hashToken(token:string){const bytes=new TextEncoder().encode(token);const digest=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("");}
export function expiresIn(hours:number){return new Date(Date.now()+hours*60*60*1000).toISOString();}
export async function rateLimit(bucketKey:string,limit:number,windowSeconds:number){const now=Math.floor(Date.now()/1000),threshold=now-windowSeconds,updatedAt=new Date().toISOString();await db().batch([db().prepare("INSERT INTO rate_limits(bucket_key,window_start,count,updated_at) VALUES(?,?,1,?) ON CONFLICT(bucket_key) DO UPDATE SET count=CASE WHEN rate_limits.window_start<? THEN 1 ELSE rate_limits.count+1 END,window_start=CASE WHEN rate_limits.window_start<? THEN excluded.window_start ELSE rate_limits.window_start END,updated_at=excluded.updated_at").bind(bucketKey,now,updatedAt,threshold,threshold)]);const row=await db().prepare("SELECT count FROM rate_limits WHERE bucket_key=?").bind(bucketKey).first<{count:number}>();if((row?.count||0)>limit)throw new ApiError(429,"Too many attempts. Please wait before trying again.");}
export async function publicRateLimit(request:Request,namespace:string,token:string,limit=30,windowSeconds=60){const tokenHash=await hashToken(token),cfIp=request.headers.get("cf-connecting-ip")||"",ipPart=cfIp?(await hashToken(cfIp)).slice(0,16):"no-ip";await rateLimit(`${namespace}:${ipPart}:${tokenHash.slice(0,24)}`,limit,windowSeconds);}
export function failure(error:unknown){if(error instanceof ZodError)return json({error:error.issues.map(x=>`${x.path.join('.')}: ${x.message}`).join("; ")},400);if(error instanceof ApiError)return json({error:error.message},error.status);const reference=crypto.randomUUID();console.error("ScopeLedger operation failed",{reference,message:error instanceof Error?error.message:"Unknown failure"});return json({error:"We could not save or load these records. Your input is still here; please try again.",reference},503);}
