import { env } from "cloudflare:workers";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { ZodError } from "zod";
import type { Role } from "./domain";
export class ApiError extends Error {constructor(public status:number,message:string){super(message);}}
export function db(){if(!env.DB)throw new ApiError(503,"Records are temporarily unavailable. Please try again.");return env.DB;}
export async function identity(){const u=await getChatGPTUser();if(!u)throw new ApiError(401,"Sign in with ChatGPT to open your workspace.");return {...u,email:u.email.toLowerCase()};}
export async function authorize(id:string){const u=await identity();const w=await db().prepare("SELECT w.*, CASE WHEN w.owner_id=? THEN 'owner' ELSE m.role END AS role FROM workspaces w LEFT JOIN members m ON m.workspace_id=w.id AND m.email=? WHERE w.id=? AND (w.owner_id=? OR m.id IS NOT NULL)").bind(u.userId,u.email,id,u.userId).first<{id:string;owner_id:string;name:string;currency:string;demo:number;role:Role}>();if(!w)throw new ApiError(404,"Workspace not found or access was removed.");return {u,w};}
export function requireRole(role:Role,roles:Role[]){if(!roles.includes(role))throw new ApiError(403,"Your workspace role does not allow this action.");}
export async function body(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new ApiError(403,"Cross-origin changes are not allowed.");if(request.headers.get("sec-fetch-site")==="cross-site")throw new ApiError(403,"Cross-site changes are not allowed.");if(!request.headers.get("content-type")?.includes("application/json"))throw new ApiError(415,"Use JSON for this request.");const raw=await request.text();if(raw.length>30000)throw new ApiError(413,"This request is too large.");try{return JSON.parse(raw);}catch{throw new ApiError(400,"Invalid JSON.");}}
export function audit(workspace:string,entity:string,action:string,actor:string,detail:string){return db().prepare("INSERT INTO events(id,workspace_id,entity_id,action,actor,detail,created_at) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),workspace,entity,action,actor,detail,new Date().toISOString());}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});}
export function failure(error:unknown){if(error instanceof ZodError)return json({error:error.issues.map(x=>`${x.path.join('.')}: ${x.message}`).join("; ")},400);if(error instanceof ApiError)return json({error:error.message},error.status);console.error("ScopeLedger operation failed",error instanceof Error?error.message:"Unknown failure");return json({error:"We could not save or load these records. Your input is still here; please try again."},503);}
