import { sqliteTable, text, integer, uniqueIndex, index } from "drizzle-orm/sqlite-core";
export const workspaces = sqliteTable("workspaces", {
 id:text("id").primaryKey(), owner_id:text("owner_id").notNull(), name:text("name").notNull(), currency:text("currency").notNull(), created_at:text("created_at").notNull(), demo:integer("demo").notNull().default(0)
},t=>[index("idx_workspaces_owner").on(t.owner_id)]);
export const members = sqliteTable("members", {
 id:text("id").primaryKey(), workspace_id:text("workspace_id").notNull().references(()=>workspaces.id), email:text("email").notNull(), role:text("role").notNull(), created_at:text("created_at").notNull()
},t=>[uniqueIndex("idx_members_workspace_email").on(t.workspace_id,t.email),index("idx_members_email").on(t.email)]);
export const invitations = sqliteTable("invitations", {
 id:text("id").primaryKey(), workspace_id:text("workspace_id").notNull().references(()=>workspaces.id), email:text("email").notNull(), role:text("role").notNull(), token_hash:text("token_hash").notNull(), expires_at:text("expires_at").notNull(), revoked_at:text("revoked_at").notNull().default(""), accepted_at:text("accepted_at").notNull().default(""), created_by:text("created_by").notNull(), created_at:text("created_at").notNull()
},t=>[uniqueIndex("idx_invitations_token_hash").on(t.token_hash),index("idx_invitations_workspace_email").on(t.workspace_id,t.email)]);
export const projects = sqliteTable("projects", {
 id:text("id").primaryKey(), workspace_id:text("workspace_id").notNull().references(()=>workspaces.id), name:text("name").notNull(), client:text("client").notNull(), client_email:text("client_email").notNull(), scope:text("scope").notNull(), budget:integer("budget").notNull(), rate:integer("rate").notNull(), due_date:text("due_date").notNull(), created_at:text("created_at").notNull(), archived_at:text("archived_at").notNull().default("")
},t=>[index("idx_projects_workspace").on(t.workspace_id)]);
export const projectAmendments = sqliteTable("project_amendments", {
 id:text("id").primaryKey(), workspace_id:text("workspace_id").notNull().references(()=>workspaces.id), project_id:text("project_id").notNull().references(()=>projects.id), version:integer("version").notNull(), scope:text("scope").notNull(), budget:integer("budget").notNull(), rate:integer("rate").notNull(), due_date:text("due_date").notNull(), reason:text("reason").notNull(), created_by:text("created_by").notNull(), created_at:text("created_at").notNull()
},t=>[uniqueIndex("idx_project_amendments_project_version").on(t.project_id,t.version),index("idx_project_amendments_workspace").on(t.workspace_id)]);
export const changes = sqliteTable("changes", {
 id:text("id").primaryKey(), workspace_id:text("workspace_id").notNull().references(()=>workspaces.id), project_id:text("project_id").notNull().references(()=>projects.id), title:text("title").notNull(), description:text("description").notNull(), source:text("source").notNull(), minutes:integer("minutes").notNull(), rate:integer("rate").notNull(), amount:integer("amount").notNull(), delay_days:integer("delay_days").notNull(), due_date:text("due_date").notNull(), status:text("status").notNull().default("pending"), approver:text("approver").notNull().default(""), evidence:text("evidence").notNull().default(""), created_by:text("created_by").notNull(), created_at:text("created_at").notNull(), updated_at:text("updated_at").notNull(), version:integer("version").notNull().default(1), pricing_mode:text("pricing_mode").notNull().default("hourly"), line_items:text("line_items").notNull().default("[]"), exclusions:text("exclusions").notNull().default(""), proposal_version:integer("proposal_version").notNull().default(1), approved_proposal_version:integer("approved_proposal_version").notNull().default(0), decision_source:text("decision_source").notNull().default(""), decided_at:text("decided_at").notNull().default(""), approved_amount:integer("approved_amount").notNull().default(0), delivered_amount:integer("delivered_amount").notNull().default(0), invoiced_amount:integer("invoiced_amount").notNull().default(0), paid_amount:integer("paid_amount").notNull().default(0)
},t=>[index("idx_changes_workspace").on(t.workspace_id),index("idx_changes_project").on(t.project_id)]);
export const proposals = sqliteTable("proposals", {
 id:text("id").primaryKey(), workspace_id:text("workspace_id").notNull().references(()=>workspaces.id), change_id:text("change_id").notNull().references(()=>changes.id), version:integer("version").notNull(), title:text("title").notNull(), description:text("description").notNull(), pricing_mode:text("pricing_mode").notNull(), line_items:text("line_items").notNull(), exclusions:text("exclusions").notNull(), minutes:integer("minutes").notNull(), rate:integer("rate").notNull(), amount:integer("amount").notNull(), delay_days:integer("delay_days").notNull(), due_date:text("due_date").notNull(), scope_snapshot:text("scope_snapshot").notNull(), project_budget:integer("project_budget").notNull(), project_due_date:text("project_due_date").notNull(), project_amendment_version:integer("project_amendment_version").notNull(), created_by:text("created_by").notNull(), created_at:text("created_at").notNull()
},t=>[uniqueIndex("idx_proposals_change_version").on(t.change_id,t.version),index("idx_proposals_workspace").on(t.workspace_id)]);
export const clientAccessLinks = sqliteTable("client_access_links", {
 id:text("id").primaryKey(), workspace_id:text("workspace_id").notNull().references(()=>workspaces.id), change_id:text("change_id").notNull().references(()=>changes.id), proposal_version:integer("proposal_version").notNull(), token_hash:text("token_hash").notNull(), client_email:text("client_email").notNull(), expires_at:text("expires_at").notNull(), revoked_at:text("revoked_at").notNull().default(""), used_at:text("used_at").notNull().default(""), created_by:text("created_by").notNull(), created_at:text("created_at").notNull()
},t=>[uniqueIndex("idx_client_access_token_hash").on(t.token_hash),index("idx_client_access_change").on(t.change_id)]);
export const events = sqliteTable("events", {
 id:text("id").primaryKey(), workspace_id:text("workspace_id").notNull().references(()=>workspaces.id), entity_id:text("entity_id").notNull(), action:text("action").notNull(), actor:text("actor").notNull(), detail:text("detail").notNull(), created_at:text("created_at").notNull()
},t=>[index("idx_events_workspace_created").on(t.workspace_id,t.created_at)]);
