import { identity,authorize,db,body,json,failure,audit,ApiError } from "@/lib/server";
import { workspaceInput } from "@/lib/domain";
export async function GET(request:Request){try{
 const u=await identity();const workspaces=(await db().prepare("SELECT w.id,w.name,w.currency,w.demo,CASE WHEN w.owner_id=? THEN 'owner' ELSE m.role END AS role FROM workspaces w LEFT JOIN members m ON m.workspace_id=w.id AND m.email=? WHERE w.owner_id=? OR m.id IS NOT NULL ORDER BY w.created_at DESC").bind(u.userId,u.email,u.userId).all()).results;
 const id=new URL(request.url).searchParams.get("id")||(workspaces[0]?.id as string);const empty={user:{email:u.email,displayName:u.displayName},workspaces,workspace:null,projects:[],project_amendments:[],changes:[],events:[],members:[]};if(!id)return json(empty);
 const {w}=await authorize(id);const results=await db().batch([db().prepare("SELECT * FROM projects WHERE workspace_id=? ORDER BY created_at DESC").bind(id),db().prepare("SELECT id,project_id,version,scope,budget,rate,due_date,reason,created_by,created_at FROM project_amendments WHERE workspace_id=? ORDER BY project_id,version DESC").bind(id),db().prepare("SELECT * FROM changes WHERE workspace_id=? ORDER BY created_at DESC").bind(id),db().prepare("SELECT * FROM events WHERE workspace_id=? ORDER BY created_at DESC LIMIT 500").bind(id),db().prepare("SELECT id,email,role FROM members WHERE workspace_id=? ORDER BY created_at").bind(id)]);
 return json({...empty,workspace:{id:w.id,name:w.name,currency:w.currency,demo:w.demo,role:w.role},projects:results[0].results,project_amendments:results[1].results,changes:results[2].results,events:results[3].results,members:results[4].results});
}catch(e){return failure(e);}}
export async function POST(request:Request){try{
 const u=await identity();const input=workspaceInput.parse(await body(request));const count=await db().prepare("SELECT COUNT(*) AS n FROM workspaces WHERE owner_id=?").bind(u.userId).first<{n:number}>();if((count?.n||0)>=20)throw new ApiError(409,"This account has reached the 20-workspace pilot limit.");
 const id=crypto.randomUUID(),now=new Date().toISOString();const operations=[db().prepare("INSERT INTO workspaces(id,owner_id,name,currency,created_at,demo) VALUES(?,?,?,?,?,?)").bind(id,u.userId,input.name,input.currency,now,input.demo?1:0),audit(id,id,"Workspace created",u.email,input.name)];
 if(input.demo){const date=(days:number)=>new Date(Date.now()+days*86400000).toISOString().slice(0,10);const samples=[{name:"Commerce platform",client:"Northstar Retail",email:"ops@northstar.example",budget:48000000,scope:"Responsive storefront, 12 product templates, standard checkout, and two design revision rounds. Excludes ERP integration and custom analytics."},{name:"Brand & launch",client:"Acme Studio",email:"team@acme.example",budget:18000000,scope:"Brand identity, 8 landing page sections, and launch assets for two channels. Excludes extra language versions and animation."},{name:"Customer portal",client:"Orbit Logistics",email:"ops@orbit.example",budget:32000000,scope:"Customer login, shipment list, invoice download, and one admin role. Excludes SMS delivery, custom roles, and report scheduling."}];
 const ids=samples.map(()=>crypto.randomUUID());samples.forEach((p,i)=>operations.push(db().prepare("INSERT INTO projects(id,workspace_id,name,client,client_email,scope,budget,rate,due_date,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(ids[i],id,p.name,p.client,p.email,p.scope,p.budget,250000,date(30+i*7),now)));
 const requests=[{p:0,title:"Add ERP inventory sync",desc:"Sync warehouse inventory to the storefront every 15 minutes. This integration is excluded from the original agreement.",minutes:1080,delay:3,status:"pending"},{p:1,title:"Three additional landing pages",desc:"Create three campaign-specific landing pages beyond the eight agreed page sections.",minutes:720,delay:2,status:"pending"},{p:2,title:"SMS shipment notifications",desc:"Add SMS status updates using the client's messaging provider. Provider charges remain separate.",minutes:480,delay:1,status:"approved"},{p:0,title:"Custom sales dashboard",desc:"Build a weekly sales dashboard with category filters and an export action.",minutes:600,delay:2,status:"delivered"},{p:1,title:"Animated brand introduction",desc:"Produce a 15-second animated brand introduction outside the agreed static brand kit.",minutes:960,delay:4,status:"rejected"}];
 requests.forEach((r,i)=>{const cid=crypto.randomUUID(),approved=["approved","delivered"].includes(r.status),amount=Math.round(r.minutes*250000/60);operations.push(db().prepare("INSERT INTO changes(id,workspace_id,project_id,title,description,source,minutes,rate,amount,delay_days,due_date,status,approver,evidence,created_by,created_at,updated_at,version,approved_proposal_version,decision_source,decided_at,approved_amount,delivered_amount) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?,?,?,?)").bind(cid,id,ids[r.p],r.title,r.desc,"Fictional sample client email — for demonstration only",r.minutes,250000,amount,r.delay,date(i===0?-2:i+2),r.status,approved?samples[r.p].email:"",approved?"Fictional demonstration approval; no real client has approved this work.":r.status==="rejected"?"Sample client chose to keep the original scope.":"",u.email,now,now,approved?1:0,approved?"staff_recorded":"",approved?now:"",approved?amount:0,r.status==="delivered"?amount:0));if(r.status!=="draft")operations.push(db().prepare("INSERT INTO proposals(id,workspace_id,change_id,version,title,description,pricing_mode,line_items,exclusions,minutes,rate,amount,delay_days,due_date,created_by,created_at) VALUES(?,?,?,?,?,?,'hourly','[]','',?,?,?,?,?,?,?)").bind(crypto.randomUUID(),id,cid,1,r.title,r.desc,r.minutes,250000,amount,r.delay,date(i===0?-2:i+2),u.email,now));operations.push(audit(id,cid,"Sample request added",u.email,r.title+" (fictional)"));});}
 await db().batch(operations);return json({id},201);
}catch(e){return failure(e);}}
